.\"     Title: vmpk
.\"    Author: Mehdi Dogguy <dogguy@pps.jussieu.fr>
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: June 7, 2009
.\"    Manual: User Commands
.\"    Source: vmpk
.\"
.TH "VMPK" "1" "June 7, 2009" "vmpk" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vmpk - Virtual MIDI Piano Keyboard
.SH "SYNOPSIS"
.HP 5
\fBvmpk\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBvmpk\fR
program\.
.PP
This program has no command\-line options\.
.PP
Virtual MIDI Piano Keyboard is a MIDI events generator and receiver\. It doesn\'t produce any sound by itself, but can be used to drive a MIDI synthesizer (either hardware or software, internal or external)\. You can use the computer\'s keyboard to play MIDI notes, and also the mouse\. You can use the Virtual MIDI Piano Keyboard to display the played MIDI notes from another instrument or MIDI file player\.
.SH "LICENSE"
.PP
This manual page was written by
Mehdi Dogguy
<dogguy@pps\.jussieu\.fr>
for the Debian GNU/Linux system (but may be used by others)\. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 or any later version published by the Free Software Foundation; considering as source code all the file that enable the production of this manpage\.
.SH "AUTHOR"
.PP
\fBMehdi Dogguy\fR <\&dogguy@pps\.jussieu\.fr\&>
.sp -1n
.IP "" 4

.SH "COPYRIGHT"
Copyright \(co 2009 Mehdi Dogguy
.br
